version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: local
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
  chromadb:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./db:/db
    environment:
      - ANONYMIZED_TELEMETRY=False